name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: install
      run: yarn install

    - name: test
      run: yarn lint

    - name: prepare
      env:
        CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
      run: echo -e "NODE_ENV='production'\nVUE_APP_TWITCH_CLIENT_ID='$CLIENT_ID'" > .env.production

    - name: show
      run: cat .env.production

    - name: build
      run: yarn build

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./docs
